openapi: 3.0.0
info:
  title: Book API
  version: 0.0.1
servers:
  - url: /
    description: Default server
security: []
tags:
  - name: books
    description: Manage books
  - name: documents
    description: upload book documents
paths:
  /books:
    $ref: paths/books.yaml
  /books/search:
    $ref: paths/books_search.yaml
  /books/{bookID}:
    $ref: paths/books_{bookID}.yaml
  /books/{bookID}/documents:
    $ref: paths/books_{bookID}_documents.yaml
  /books/{bookID}/documents/presign:
    $ref: paths/books_{bookID}_documents_presign.yaml
  /books/{bookID}/documents/{documentID}:
    $ref: paths/books_{bookID}_documents_{documentID}.yaml
  /books/{bookID}/documents/{documentID}/complete:
    $ref: paths/books_{bookID}_documents_{documentID}_complete.yaml
  /books/{bookID}/documents/{documentID}/download:
    $ref: paths/books_{bookID}_documents_{documentID}_download.yaml
