openapi: 3.0.0
info:
  title: Book API
  version: 0.0.1
tags:
  - name: books
    description: Manage books
  - name: documents
    description: upload book documents
paths:
  /books:
    $ref: paths/books.yaml
  /books/search:
    $ref: paths/books_search.yaml
  /books/{bookID}:
    $ref: paths/books_{bookID}.yaml
  /books/{bookID}documents:
    post:
      responses:
        default:
          description: "successful"
      deprecated: false
  /books/{bookID}documents/{documentID}:
    delete:
      responses:
        default:
          description: "successful"
      deprecated: false
